amiId = 'ami-0a0e75afb55700243'
MAX_INSTANCES = 10
MIN_INSTANCES = 1
Monitoring = {'Enabled': True}
grow_rate = 2
shrink_rate = 2
grow_threshold = 45
shrink_threshold = 15
LoadBalancerName = 'ECE1779A2'
InstanceType = "t2.small"
KeyName = "ECE_1779"
TagSpecifications = [{'ResourceType':'instance','Tags': [{'Key': 'Name','Value': 'worker'},]},]
Placement = {'AvailabilityZone':'us-east-1a'}
SecurityGroupId = ['sg-0cb45848244a0c96e']
SecurityGroups = ['launch-wizard-1']
SubnetId = 'subnet-3604876a'
UserData = '#!/bin/bash\ncd /home/ubuntu/Desktop/web-development-Cloud-Computing/webapp\n. venv/bin/activate\n./venv/bin/gunicorn -w 10 -k gevent -b 0.0.0.0:5000 app:webapp'
Auto_scaling = False
